platform :ios, '9.0'

target 'Kittygram' do
  use_frameworks!

  pod 'Moya-ModelMapper/RxSwift'
  pod 'RxCocoa'

  target 'KittygramTests' do
    inherit! :search_paths
    
    pod 'Quick', '0.10.0'
    pod 'Nimble', '5.0.0'
  end

end
